# build stage
FROM node:20-alpine as build

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .


RUN npm run build
ENV VITE_API_BASE_URL=https://redex-be.congcucuatoi.com
EXPOSE 3000


CMD ["npm", "run", "start", "--", "--host"]
