version: "3.9"

services:
  react-app:
    build:
      context: .
      dockerfile: ./dockerfile.prod
    container_name: redex_frontend
    environment:
      - VITE_API_BASE_URL=https://redex-be.congcucuatoi.com/
    ports:
      - "2046:3000"
    volumes:
      - /hthai/jenkins_data/workspace/redex_frontend:/app
    command: ["npm", "run", "start", "--", "--host",]
