version: "3.9"

services:
  redex_frontend:
    build: .
    container_name: redex_frontend
    ports:
      - "2046:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "dev", "--", "--host",]